# Generated by Django 2.1.7 on 2019-07-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fok', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_greeted',
            field=models.BooleanField(default=False),
        ),
    ]
