# Generated by Django 2.1.7 on 2019-07-07 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fok', '0002_user_is_greeted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fok.Background', verbose_name='Research Field'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
