version: '3'

services:
  fok_app:
    image: fok_platform
    # build: ./
    restart: always
    networks:
      - mynetwork
    expose:
      - "8080"
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - /home/coopersmout/git/platform/apps:/src/apps
      - /home/coopersmout/git/platform/free_our_knowledge:/src/free_our_knowledge

  db:
    image: postgres
    restart: always
    networks:
      - mynetwork
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "mysecretpassword"
      POSTGRES_DB: "fok"
    expose:
      - "5432"
    ports:
      - "5432:5432"

networks: {mynetwork: {}}
